version: '3'
services:
  app:
    build:
        context: .
        dockerfile: DockerFile
    container_name: 'vision_access'
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /visionapi.json
    volumes:
      - ~/docker_home/vision_api:/home
      - ~/docker_home/google_key/visionapi.json:/visionapi.json
    tty: true
